// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geladfgknfnqwaozdhxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbGFkZmdrbmZucXdhb3pkaHhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzkyNTAsImV4cCI6MjA2MzUxNTI1MH0.lq8GOPtodRLtsjFbIwB7VRyiex9G5FLOlefOPKafWdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);